{
//=========Macro generated from canvas: c1/plots
//=========  (Mon Apr 16 17:28:49 2018) by ROOT version5.34/30
   TCanvas *c1 = new TCanvas("c1", "plots",0,45,900,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(10);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.15);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillColor(0);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: p2
   TPad *p2 = new TPad("p2", "pad1",0.01,0.01,0.99,0.99);
   p2->Draw();
   p2->cd();
   p2->Range(-0.1801769,-2.013141,4.552477,0.4222944);
   p2->SetFillColor(10);
   p2->SetBorderMode(0);
   p2->SetBorderSize(2);
   p2->SetLogx();
   p2->SetLogy();
   p2->SetTickx(1);
   p2->SetTicky(1);
   p2->SetRightMargin(0.01);
   p2->SetTopMargin(0.01);
   p2->SetBottomMargin(0.129);
   p2->SetFrameFillColor(0);
   p2->SetFrameBorderMode(0);
   p2->SetFrameBorderMode(0);
   
   TH2F *h5 = new TH2F("h5","",1,1.88,32000,1,0.02,2.5);
   h5->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   h5->SetLineColor(ci);
   h5->GetXaxis()->SetTitle("#sqrt{#it{s}} (GeV)");
   h5->GetXaxis()->SetLabelFont(42);
   h5->GetXaxis()->SetLabelSize(0.05);
   h5->GetXaxis()->SetTitleSize(0.06);
   h5->GetXaxis()->SetTitleOffset(1.1);
   h5->GetXaxis()->SetTitleFont(42);
   h5->GetYaxis()->SetTitle("(#Sigma^{0}+#bar{#Sigma}^{0}) / 2#Lambda");
   h5->GetYaxis()->SetLabelFont(42);
   h5->GetYaxis()->SetLabelSize(0.05);
   h5->GetYaxis()->SetTitleSize(0.06);
   h5->GetYaxis()->SetTitleOffset(0.9);
   h5->GetYaxis()->SetTitleFont(42);
   h5->GetZaxis()->SetLabelFont(42);
   h5->GetZaxis()->SetLabelSize(0.035);
   h5->GetZaxis()->SetTitleSize(0.035);
   h5->GetZaxis()->SetTitleFont(42);
   h5->Draw("");
   
   TGraphErrors *gre = new TGraphErrors(1);
   gre->SetName("Graph0");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetLineColor(4);
   gre->SetMarkerColor(4);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.5);
   gre->SetPoint(0,10,0.33);
   gre->SetPointError(0,0,0.1);
   
   TH1F *Graph_Graph1 = new TH1F("Graph_Graph1","Graph",100,9.9,11.1);
   Graph_Graph1->SetMinimum(0.21);
   Graph_Graph1->SetMaximum(0.45);
   Graph_Graph1->SetDirectory(0);
   Graph_Graph1->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   Graph_Graph1->SetLineColor(ci);
   Graph_Graph1->GetXaxis()->SetLabelFont(42);
   Graph_Graph1->GetXaxis()->SetLabelOffset(0.01);
   Graph_Graph1->GetXaxis()->SetLabelSize(0.045);
   Graph_Graph1->GetXaxis()->SetTitleSize(0.05);
   Graph_Graph1->GetXaxis()->SetTitleOffset(1.2);
   Graph_Graph1->GetXaxis()->SetTitleFont(42);
   Graph_Graph1->GetYaxis()->SetLabelFont(42);
   Graph_Graph1->GetYaxis()->SetLabelOffset(0.015);
   Graph_Graph1->GetYaxis()->SetLabelSize(0.045);
   Graph_Graph1->GetYaxis()->SetTitleSize(0.05);
   Graph_Graph1->GetYaxis()->SetTitleOffset(0.9);
   Graph_Graph1->GetYaxis()->SetTitleFont(42);
   Graph_Graph1->GetZaxis()->SetLabelFont(42);
   Graph_Graph1->GetZaxis()->SetLabelSize(0.045);
   Graph_Graph1->GetZaxis()->SetTitleSize(0.05);
   Graph_Graph1->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph1);
   
   gre->Draw("p");
   
   gre = new TGraphErrors(2);
   gre->SetName("Graph1");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerStyle(25);
   gre->SetMarkerSize(1.5);
   gre->SetPoint(0,5.734498,0.15131);
   gre->SetPointError(0,0,0.089881);
   gre->SetPoint(1,4.833222,0.49375);
   gre->SetPointError(1,0,0.048565);
   
   TH1F *Graph_Graph2 = new TH1F("Graph_Graph2","Graph",100,4.743094,5.824626);
   Graph_Graph2->SetMinimum(0.01334039);
   Graph_Graph2->SetMaximum(0.5904036);
   Graph_Graph2->SetDirectory(0);
   Graph_Graph2->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   Graph_Graph2->SetLineColor(ci);
   Graph_Graph2->GetXaxis()->SetLabelFont(42);
   Graph_Graph2->GetXaxis()->SetLabelOffset(0.01);
   Graph_Graph2->GetXaxis()->SetLabelSize(0.045);
   Graph_Graph2->GetXaxis()->SetTitleSize(0.05);
   Graph_Graph2->GetXaxis()->SetTitleOffset(1.2);
   Graph_Graph2->GetXaxis()->SetTitleFont(42);
   Graph_Graph2->GetYaxis()->SetLabelFont(42);
   Graph_Graph2->GetYaxis()->SetLabelOffset(0.015);
   Graph_Graph2->GetYaxis()->SetLabelSize(0.045);
   Graph_Graph2->GetYaxis()->SetTitleSize(0.05);
   Graph_Graph2->GetYaxis()->SetTitleOffset(0.9);
   Graph_Graph2->GetYaxis()->SetTitleFont(42);
   Graph_Graph2->GetZaxis()->SetLabelFont(42);
   Graph_Graph2->GetZaxis()->SetLabelSize(0.045);
   Graph_Graph2->GetZaxis()->SetTitleSize(0.05);
   Graph_Graph2->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph2);
   
   gre->Draw("p");
   
   gre = new TGraphErrors(4);
   gre->SetName("Graph2");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetLineColor(2);
   gre->SetMarkerColor(2);
   gre->SetMarkerStyle(21);
   gre->SetMarkerSize(1.5);
   gre->SetPoint(0,7.78,0.56);
   gre->SetPointError(0,0,0.21);
   gre->SetPoint(1,23.564,0.52);
   gre->SetPointError(1,0,0.25);
   gre->SetPoint(2,7000,0.337);
   gre->SetPointError(2,0,0.092);
   gre->SetPoint(3,7000,0.337);
   gre->SetPointError(3,0,0.051);
   
   TH1F *Graph_Graph3 = new TH1F("Graph_Graph3","Graph",100,7.002,7699.222);
   Graph_Graph3->SetMinimum(0.1925);
   Graph_Graph3->SetMaximum(0.8225);
   Graph_Graph3->SetDirectory(0);
   Graph_Graph3->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   Graph_Graph3->SetLineColor(ci);
   Graph_Graph3->GetXaxis()->SetLabelFont(42);
   Graph_Graph3->GetXaxis()->SetLabelOffset(0.01);
   Graph_Graph3->GetXaxis()->SetLabelSize(0.045);
   Graph_Graph3->GetXaxis()->SetTitleSize(0.05);
   Graph_Graph3->GetXaxis()->SetTitleOffset(1.2);
   Graph_Graph3->GetXaxis()->SetTitleFont(42);
   Graph_Graph3->GetYaxis()->SetLabelFont(42);
   Graph_Graph3->GetYaxis()->SetLabelOffset(0.015);
   Graph_Graph3->GetYaxis()->SetLabelSize(0.045);
   Graph_Graph3->GetYaxis()->SetTitleSize(0.05);
   Graph_Graph3->GetYaxis()->SetTitleOffset(0.9);
   Graph_Graph3->GetYaxis()->SetTitleFont(42);
   Graph_Graph3->GetZaxis()->SetLabelFont(42);
   Graph_Graph3->GetZaxis()->SetLabelSize(0.045);
   Graph_Graph3->GetZaxis()->SetTitleSize(0.05);
   Graph_Graph3->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph3);
   
   gre->Draw("p");
   
   gre = new TGraphErrors(1);
   gre->SetName("Graph3");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetLineColor(2);
   gre->SetMarkerColor(2);
   gre->SetMarkerStyle(24);
   gre->SetMarkerSize(1.5);
   gre->SetPoint(0,7.434,0.278);
   gre->SetPointError(0,0,0.051);
   
   TH1F *Graph_Graph4 = new TH1F("Graph_Graph4","Graph",100,7.334,8.534);
   Graph_Graph4->SetMinimum(0.2168);
   Graph_Graph4->SetMaximum(0.3392);
   Graph_Graph4->SetDirectory(0);
   Graph_Graph4->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   Graph_Graph4->SetLineColor(ci);
   Graph_Graph4->GetXaxis()->SetLabelFont(42);
   Graph_Graph4->GetXaxis()->SetLabelOffset(0.01);
   Graph_Graph4->GetXaxis()->SetLabelSize(0.045);
   Graph_Graph4->GetXaxis()->SetTitleSize(0.05);
   Graph_Graph4->GetXaxis()->SetTitleOffset(1.2);
   Graph_Graph4->GetXaxis()->SetTitleFont(42);
   Graph_Graph4->GetYaxis()->SetLabelFont(42);
   Graph_Graph4->GetYaxis()->SetLabelOffset(0.015);
   Graph_Graph4->GetYaxis()->SetLabelSize(0.045);
   Graph_Graph4->GetYaxis()->SetTitleSize(0.05);
   Graph_Graph4->GetYaxis()->SetTitleOffset(0.9);
   Graph_Graph4->GetYaxis()->SetTitleFont(42);
   Graph_Graph4->GetZaxis()->SetLabelFont(42);
   Graph_Graph4->GetZaxis()->SetLabelSize(0.045);
   Graph_Graph4->GetZaxis()->SetTitleSize(0.05);
   Graph_Graph4->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph4);
   
   gre->Draw("p");
   
   gre = new TGraphErrors(1);
   gre->SetName("Graph4");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetLineColor(2);
   gre->SetMarkerColor(2);
   gre->SetMarkerStyle(27);
   gre->SetMarkerSize(1.5);
   gre->SetPoint(0,23.964,0.43);
   gre->SetPointError(0,0,0.24);
   
   TH1F *Graph_Graph5 = new TH1F("Graph_Graph5","Graph",100,23.864,25.064);
   Graph_Graph5->SetMinimum(0.142);
   Graph_Graph5->SetMaximum(0.718);
   Graph_Graph5->SetDirectory(0);
   Graph_Graph5->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   Graph_Graph5->SetLineColor(ci);
   Graph_Graph5->GetXaxis()->SetLabelFont(42);
   Graph_Graph5->GetXaxis()->SetLabelOffset(0.01);
   Graph_Graph5->GetXaxis()->SetLabelSize(0.045);
   Graph_Graph5->GetXaxis()->SetTitleSize(0.05);
   Graph_Graph5->GetXaxis()->SetTitleOffset(1.2);
   Graph_Graph5->GetXaxis()->SetTitleFont(42);
   Graph_Graph5->GetYaxis()->SetLabelFont(42);
   Graph_Graph5->GetYaxis()->SetLabelOffset(0.015);
   Graph_Graph5->GetYaxis()->SetLabelSize(0.045);
   Graph_Graph5->GetYaxis()->SetTitleSize(0.05);
   Graph_Graph5->GetYaxis()->SetTitleOffset(0.9);
   Graph_Graph5->GetYaxis()->SetTitleFont(42);
   Graph_Graph5->GetZaxis()->SetLabelFont(42);
   Graph_Graph5->GetZaxis()->SetLabelSize(0.045);
   Graph_Graph5->GetZaxis()->SetTitleSize(0.05);
   Graph_Graph5->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph5);
   
   gre->Draw("p");
   TLine *line = new TLine(1.8766,0.02,1.8766,0.0212);
   line->SetLineWidth(2);
   line->Draw();
   line = new TLine(1.8767,0.02,1.8767,0.0212);
   line->SetLineWidth(2);
   line->Draw();
   line = new TLine(1.8768,0.02,1.8768,0.0212);
   line->SetLineWidth(2);
   line->Draw();
   line = new TLine(1.8769,0.02,1.8769,0.0212);
   line->SetLineWidth(2);
   line->Draw();
   line = new TLine(1.877,0.02,1.877,0.0212);
   line->SetLineWidth(2);
   line->Draw();
   line = new TLine(1.8771,0.02,1.8771,0.0212);
   line->SetLineWidth(2);
   line->Draw();
   line = new TLine(1.8772,0.02,1.8772,0.0212);
   line->SetLineWidth(2);
   line->Draw();
   line = new TLine(1.8773,0.02,1.8773,0.0212);
   line->SetLineWidth(2);
   line->Draw();
   line = new TLine(1.8774,0.02,1.8774,0.0212);
   line->SetLineWidth(2);
   line->Draw();
   line = new TLine(1.8775,0.02,1.8775,0.0228);
   line->SetLineWidth(2);
   line->Draw();
   
   TLegend *leg = new TLegend(0.5,0.19,0.8,0.55,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(2);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("NULL","Collision systems:","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph0","e^{+}e^{-}","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(4);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph1","#bar{p}p","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(25);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph2","pp","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(2);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph3","p-Be","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(2);
   entry->SetMarkerStyle(24);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph4","p-Ne","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(2);
   entry->SetMarkerStyle(27);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.38,0.87,"ALICE,  pp #sqrt{#it{s}} = 7 TeV");
   tex->SetTextFont(42);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.77,"Uncertainties: stat. (inner bars), sys. (outer bars)");
   tex->SetTextFont(42);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
   p2->Modified();
   c1->cd();
   
   gre = new TGraphErrors(1);
   gre->SetName("Graph0");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetLineColor(4);
   gre->SetMarkerColor(4);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.5);
   gre->SetPoint(0,10,0.33);
   gre->SetPointError(0,0,0.1);
   
   TH1F *Graph_Graph_Graph16 = new TH1F("Graph_Graph_Graph16","Graph",100,9.9,11.1);
   Graph_Graph_Graph16->SetMinimum(0.21);
   Graph_Graph_Graph16->SetMaximum(0.45);
   Graph_Graph_Graph16->SetDirectory(0);
   Graph_Graph_Graph16->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   Graph_Graph_Graph16->SetLineColor(ci);
   Graph_Graph_Graph16->GetXaxis()->SetLabelFont(42);
   Graph_Graph_Graph16->GetXaxis()->SetLabelOffset(0.01);
   Graph_Graph_Graph16->GetXaxis()->SetLabelSize(0.045);
   Graph_Graph_Graph16->GetXaxis()->SetTitleSize(0.05);
   Graph_Graph_Graph16->GetXaxis()->SetTitleOffset(1.2);
   Graph_Graph_Graph16->GetXaxis()->SetTitleFont(42);
   Graph_Graph_Graph16->GetYaxis()->SetLabelFont(42);
   Graph_Graph_Graph16->GetYaxis()->SetLabelOffset(0.015);
   Graph_Graph_Graph16->GetYaxis()->SetLabelSize(0.045);
   Graph_Graph_Graph16->GetYaxis()->SetTitleSize(0.05);
   Graph_Graph_Graph16->GetYaxis()->SetTitleOffset(0.9);
   Graph_Graph_Graph16->GetYaxis()->SetTitleFont(42);
   Graph_Graph_Graph16->GetZaxis()->SetLabelFont(42);
   Graph_Graph_Graph16->GetZaxis()->SetLabelSize(0.045);
   Graph_Graph_Graph16->GetZaxis()->SetTitleSize(0.05);
   Graph_Graph_Graph16->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph_Graph16);
   
   gre->Draw("p");
   
   gre = new TGraphErrors(2);
   gre->SetName("Graph1");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerStyle(25);
   gre->SetMarkerSize(1.5);
   gre->SetPoint(0,5.734498,0.15131);
   gre->SetPointError(0,0,0.089881);
   gre->SetPoint(1,4.833222,0.49375);
   gre->SetPointError(1,0,0.048565);
   
   TH1F *Graph_Graph_Graph27 = new TH1F("Graph_Graph_Graph27","Graph",100,4.743094,5.824626);
   Graph_Graph_Graph27->SetMinimum(0.01334039);
   Graph_Graph_Graph27->SetMaximum(0.5904036);
   Graph_Graph_Graph27->SetDirectory(0);
   Graph_Graph_Graph27->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   Graph_Graph_Graph27->SetLineColor(ci);
   Graph_Graph_Graph27->GetXaxis()->SetLabelFont(42);
   Graph_Graph_Graph27->GetXaxis()->SetLabelOffset(0.01);
   Graph_Graph_Graph27->GetXaxis()->SetLabelSize(0.045);
   Graph_Graph_Graph27->GetXaxis()->SetTitleSize(0.05);
   Graph_Graph_Graph27->GetXaxis()->SetTitleOffset(1.2);
   Graph_Graph_Graph27->GetXaxis()->SetTitleFont(42);
   Graph_Graph_Graph27->GetYaxis()->SetLabelFont(42);
   Graph_Graph_Graph27->GetYaxis()->SetLabelOffset(0.015);
   Graph_Graph_Graph27->GetYaxis()->SetLabelSize(0.045);
   Graph_Graph_Graph27->GetYaxis()->SetTitleSize(0.05);
   Graph_Graph_Graph27->GetYaxis()->SetTitleOffset(0.9);
   Graph_Graph_Graph27->GetYaxis()->SetTitleFont(42);
   Graph_Graph_Graph27->GetZaxis()->SetLabelFont(42);
   Graph_Graph_Graph27->GetZaxis()->SetLabelSize(0.045);
   Graph_Graph_Graph27->GetZaxis()->SetTitleSize(0.05);
   Graph_Graph_Graph27->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph_Graph27);
   
   gre->Draw("p");
   
   gre = new TGraphErrors(4);
   gre->SetName("Graph2");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetLineColor(2);
   gre->SetMarkerColor(2);
   gre->SetMarkerStyle(21);
   gre->SetMarkerSize(1.5);
   gre->SetPoint(0,7.78,0.56);
   gre->SetPointError(0,0,0.21);
   gre->SetPoint(1,23.564,0.52);
   gre->SetPointError(1,0,0.25);
   gre->SetPoint(2,7000,0.337);
   gre->SetPointError(2,0,0.092);
   gre->SetPoint(3,7000,0.337);
   gre->SetPointError(3,0,0.051);
   
   TH1F *Graph_Graph_Graph38 = new TH1F("Graph_Graph_Graph38","Graph",100,7.002,7699.222);
   Graph_Graph_Graph38->SetMinimum(0.1925);
   Graph_Graph_Graph38->SetMaximum(0.8225);
   Graph_Graph_Graph38->SetDirectory(0);
   Graph_Graph_Graph38->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   Graph_Graph_Graph38->SetLineColor(ci);
   Graph_Graph_Graph38->GetXaxis()->SetLabelFont(42);
   Graph_Graph_Graph38->GetXaxis()->SetLabelOffset(0.01);
   Graph_Graph_Graph38->GetXaxis()->SetLabelSize(0.045);
   Graph_Graph_Graph38->GetXaxis()->SetTitleSize(0.05);
   Graph_Graph_Graph38->GetXaxis()->SetTitleOffset(1.2);
   Graph_Graph_Graph38->GetXaxis()->SetTitleFont(42);
   Graph_Graph_Graph38->GetYaxis()->SetLabelFont(42);
   Graph_Graph_Graph38->GetYaxis()->SetLabelOffset(0.015);
   Graph_Graph_Graph38->GetYaxis()->SetLabelSize(0.045);
   Graph_Graph_Graph38->GetYaxis()->SetTitleSize(0.05);
   Graph_Graph_Graph38->GetYaxis()->SetTitleOffset(0.9);
   Graph_Graph_Graph38->GetYaxis()->SetTitleFont(42);
   Graph_Graph_Graph38->GetZaxis()->SetLabelFont(42);
   Graph_Graph_Graph38->GetZaxis()->SetLabelSize(0.045);
   Graph_Graph_Graph38->GetZaxis()->SetTitleSize(0.05);
   Graph_Graph_Graph38->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph_Graph38);
   
   gre->Draw("p");
   
   gre = new TGraphErrors(1);
   gre->SetName("Graph3");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetLineColor(2);
   gre->SetMarkerColor(2);
   gre->SetMarkerStyle(24);
   gre->SetMarkerSize(1.5);
   gre->SetPoint(0,7.434,0.278);
   gre->SetPointError(0,0,0.051);
   
   TH1F *Graph_Graph_Graph49 = new TH1F("Graph_Graph_Graph49","Graph",100,7.334,8.534);
   Graph_Graph_Graph49->SetMinimum(0.2168);
   Graph_Graph_Graph49->SetMaximum(0.3392);
   Graph_Graph_Graph49->SetDirectory(0);
   Graph_Graph_Graph49->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   Graph_Graph_Graph49->SetLineColor(ci);
   Graph_Graph_Graph49->GetXaxis()->SetLabelFont(42);
   Graph_Graph_Graph49->GetXaxis()->SetLabelOffset(0.01);
   Graph_Graph_Graph49->GetXaxis()->SetLabelSize(0.045);
   Graph_Graph_Graph49->GetXaxis()->SetTitleSize(0.05);
   Graph_Graph_Graph49->GetXaxis()->SetTitleOffset(1.2);
   Graph_Graph_Graph49->GetXaxis()->SetTitleFont(42);
   Graph_Graph_Graph49->GetYaxis()->SetLabelFont(42);
   Graph_Graph_Graph49->GetYaxis()->SetLabelOffset(0.015);
   Graph_Graph_Graph49->GetYaxis()->SetLabelSize(0.045);
   Graph_Graph_Graph49->GetYaxis()->SetTitleSize(0.05);
   Graph_Graph_Graph49->GetYaxis()->SetTitleOffset(0.9);
   Graph_Graph_Graph49->GetYaxis()->SetTitleFont(42);
   Graph_Graph_Graph49->GetZaxis()->SetLabelFont(42);
   Graph_Graph_Graph49->GetZaxis()->SetLabelSize(0.045);
   Graph_Graph_Graph49->GetZaxis()->SetTitleSize(0.05);
   Graph_Graph_Graph49->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph_Graph49);
   
   gre->Draw("p");
   
   gre = new TGraphErrors(1);
   gre->SetName("Graph4");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetLineColor(2);
   gre->SetMarkerColor(2);
   gre->SetMarkerStyle(27);
   gre->SetMarkerSize(1.5);
   gre->SetPoint(0,23.964,0.43);
   gre->SetPointError(0,0,0.24);
   
   TH1F *Graph_Graph_Graph510 = new TH1F("Graph_Graph_Graph510","Graph",100,23.864,25.064);
   Graph_Graph_Graph510->SetMinimum(0.142);
   Graph_Graph_Graph510->SetMaximum(0.718);
   Graph_Graph_Graph510->SetDirectory(0);
   Graph_Graph_Graph510->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   Graph_Graph_Graph510->SetLineColor(ci);
   Graph_Graph_Graph510->GetXaxis()->SetLabelFont(42);
   Graph_Graph_Graph510->GetXaxis()->SetLabelOffset(0.01);
   Graph_Graph_Graph510->GetXaxis()->SetLabelSize(0.045);
   Graph_Graph_Graph510->GetXaxis()->SetTitleSize(0.05);
   Graph_Graph_Graph510->GetXaxis()->SetTitleOffset(1.2);
   Graph_Graph_Graph510->GetXaxis()->SetTitleFont(42);
   Graph_Graph_Graph510->GetYaxis()->SetLabelFont(42);
   Graph_Graph_Graph510->GetYaxis()->SetLabelOffset(0.015);
   Graph_Graph_Graph510->GetYaxis()->SetLabelSize(0.045);
   Graph_Graph_Graph510->GetYaxis()->SetTitleSize(0.05);
   Graph_Graph_Graph510->GetYaxis()->SetTitleOffset(0.9);
   Graph_Graph_Graph510->GetYaxis()->SetTitleFont(42);
   Graph_Graph_Graph510->GetZaxis()->SetLabelFont(42);
   Graph_Graph_Graph510->GetZaxis()->SetLabelSize(0.045);
   Graph_Graph_Graph510->GetZaxis()->SetTitleSize(0.05);
   Graph_Graph_Graph510->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph_Graph510);
   
   gre->Draw("p");
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
